version: '3.8'

services:
  postgres:
    image: postgis/postgis:16-3.4
    container_name: cleancity_db
    environment:
      POSTGRES_USER: cleancity
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cleancity
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: quay.io/minio/minio
    container_name: cleancity_minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

volumes:
  postgres_data:
  minio_data:
